# Generated by Django 4.2.3 on 2023-07-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=35, verbose_name='Пароль')),
                ('login', models.CharField(blank=True, default='', max_length=40, verbose_name='Логин')),
                ('user_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Имя')),
                ('user_surname', models.CharField(blank=True, default='', max_length=25, verbose_name='Фамилия')),
                ('img_link', models.URLField(blank=True, default='', verbose_name='Ссылка на изображение для аватарки')),
                ('birthday', models.DateField(blank=True, default='', max_length=25, verbose_name='Возраст')),
                ('gender', models.CharField(default=0, max_length=20, verbose_name='Пол')),
                ('money', models.IntegerField(default=100000, verbose_name='Баланс')),
                ('products_purchased', models.IntegerField(default=0, verbose_name='Количество купленных товаров')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
