# Generated by Django 4.1.5 on 2023-07-10 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('user_surname', models.CharField(blank=True, max_length=25, verbose_name='Фамилия')),
                ('img', models.FileField(blank=True, upload_to=main.models.png_save, verbose_name='Фотография')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('country', models.CharField(blank=True, max_length=40, verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
