# Generated by Django 4.2.3 on 2023-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(blank=True, default='', max_length=25, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
