# Generated by Django 4.2.3 on 2023-07-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_birthday_alter_users_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_surname', models.CharField(blank=True, default='', max_length=25, verbose_name='Фамилия')),
                ('img_link', models.URLField(blank=True, default='', verbose_name='Ссылка на изображение для аватарки')),
                ('birthday', models.DateField(blank=True, default='', max_length=25, verbose_name='День рождения')),
                ('gender', models.CharField(default=0, max_length=20, verbose_name='Пол')),
                ('money', models.IntegerField(default=0, verbose_name='Баланс')),
                ('products_purchased', models.IntegerField(default=0, verbose_name='Количество купленных товаров')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
