# Generated by Django 4.1.5 on 2023-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, verbose_name='Имя товара')),
                ('type', models.CharField(blank=True, max_length=35, verbose_name='Тип')),
                ('size', models.CharField(blank=True, max_length=35, verbose_name='Доступные размеры')),
                ('cost', models.IntegerField(blank=True, verbose_name='Стоимость')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('brand', models.CharField(blank=True, max_length=40, verbose_name='Бренд')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
