# Generated by Django 4.1.5 on 2023-07-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='size',
        ),
        migrations.CreateModel(
            name='Item_sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_size', models.CharField(blank=True, max_length=10, verbose_name='Тип размера (страна)')),
                ('size', models.CharField(blank=True, max_length=10, verbose_name='Размер')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.items')),
            ],
        ),
    ]
