# Generated by Django 4.1.5 on 2023-08-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_basket_count_basket_item_size_basket_item_type_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(blank=True, verbose_name='ID пользователя')),
                ('offer_number', models.CharField(blank=True, max_length=50, verbose_name='Номер заказа')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Мобильный номер')),
                ('FIO', models.CharField(blank=True, max_length=50, verbose_name='ФИО')),
                ('tg', models.CharField(blank=True, max_length=50, verbose_name='Телеграм')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Почта')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('delivery', models.CharField(blank=True, max_length=50, verbose_name='Тип доставки')),
                ('payment', models.CharField(blank=True, max_length=50, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Items_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField(blank=True, verbose_name='ID товара')),
                ('item_type_size', models.CharField(blank=True, max_length=10, verbose_name='Тип размера (страна)')),
                ('item_size', models.CharField(blank=True, max_length=10, verbose_name='Размер')),
                ('count', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.purchase')),
            ],
        ),
    ]
