# Generated by Django 4.1.5 on 2023-08-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='step',
            field=models.CharField(blank=True, default='Принят', max_length=50, verbose_name='Стадия заказа'),
        ),
    ]
