# Generated by Django 4.2.3 on 2023-08-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_purchase_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, verbose_name='Товар')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='main.profile')),
            ],
        ),
    ]
