# Generated by Django 4.1.5 on 2023-08-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Запрос'),
        ),
    ]
